### PR TITLE
Update slotted select style to width: 100%;

### PR DESCRIPTION
**Pull request by miyconst**

### CODE REVIEW

**Comment by tomalec** [comment]
@alshakero could you check how it behaves in polyfilled browsers? I susspect ` ::slotted(select) ` may not be translated well enough due to https://github.com/webcomponents/shadycss#selector-scoping

**Comment by tomalec** [comment]
If it does not work well, I think it should be easier to do 
```css
:host >  ::slotted(select) {
width:100%;
}
juicy-select > select {
width:100%;
}
```

Than adding wrappers to make polyfill happy

**Review by tomalec — APPROVED** [review]
I just checked the code, without actually running the demo.

**Review by alshakero — APPROVED** [review]
I checked on FF, Edge and Chrome. All are working great without issues (the inner `select` is streching with the outer `juicy-select` as it should). But please don't merge just yet. I'll add a test for this.

**Review by alshakero — APPROVED** [review]
Feel free to merge

**Comment by miyconst** [comment]
@alshakero could you please merge it and finish whatever else is required?

**Pull request merged**
